# Generated by Django 4.0.6 on 2022-07-31 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_post', models.CharField(max_length=255, verbose_name='Titulo do Post')),
                ('data_post', models.DateTimeField(verbose_name='Data do Post')),
                ('conteudo_post', models.TextField(verbose_name='Conteudo do Post')),
                ('excerto_post', models.TextField(verbose_name='Excerto do Post')),
                ('imagem_post', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d')),
                ('publicado_post', models.BooleanField(default=False, verbose_name='Publicado ?')),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('categoria_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Posts',
            },
        ),
    ]
