# Generated by Django 4.0.6 on 2022-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_categoria_post_alter_post_conteudo_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_post',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
